"""empty message

Revision ID: 70793a652082
Revises: 
Create Date: 2020-08-05 20:14:36.153141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70793a652082'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carteira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=15), nullable=True),
    sa.Column('preco_medio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carteira')
    # ### end Alembic commands ###
